-- Supabase PostgreSQL Schema for MAMA KAY Luxury Boutique

-- 1. Create users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- 2. Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price REAL NOT NULL,
  description TEXT,
  imageUrl TEXT,
  -- Note: The app currently uses integers 0/1 for booleans in SQLite.
  -- To keep it perfectly compatible with the existing backend logic without changes,
  -- we keep these as INTEGER instead of BOOLEAN.
  isAvailable INTEGER DEFAULT 1,
  isFeatured INTEGER DEFAULT 0
);

-- 3. Create settings table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- 4. Seed initial admin user
-- Password is 'GREATVALUE222' hashed with bcrypt
INSERT INTO users (username, password) 
VALUES ('admin', '$2b$10$yWVaHFpgShEO513WwXCbLuy5h5Z/AyEgZ15n.9.CyA/V3HfzaNu.W') 
ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;

-- 5. Seed initial settings
INSERT INTO settings (key, value) VALUES
('about_us', 'We specialize in luxury shoes, premium handbags, and elegant clothing carefully selected for women who appreciate quality, confidence, and timeless fashion.

At MAMA KAY, every item reflects sophistication, comfort, and class. Our mission is to help every woman look exceptional without compromising on quality.

Whether you''re shopping for work, weddings, parties, or everyday elegance, MAMA KAY offers collections that inspire confidence and celebrate femininity.'),

('vision', 'Our vision is to become one of Nigeria''s leading luxury fashion brands, recognized for delivering premium-quality shoes, handbags, and clothing that inspire confidence, elegance, and timeless style.

We aspire to empower women through fashion by providing luxurious collections, outstanding customer service, and an unforgettable shopping experience.'),

('privacy_policy', '1. Information We Collect
When you visit our website, place an order, subscribe to our newsletter, or contact us, we may collect personal information such as your name, email address, phone number, and delivery address. We also automatically collect certain information about your device, including your web browser, IP address, and time zone.

2. How We Use Your Information
We use the order information that we collect generally to fulfill any orders placed through the website (including processing your payment information, arranging for shipping, and providing you with invoices and/or order confirmations).

3. Sharing Your Personal Information
We share your Personal Information with third parties to help us use your Personal Information, as described above. We may also share your Personal Information to comply with applicable laws and regulations.

4. Data Retention
When you place an order through the website, we will maintain your Order Information for our records unless and until you ask us to delete this information.

5. Contact Us
For more information about our privacy practices, please contact us.'),

('terms_conditions', '1. Introduction
Welcome to MAMA KAY Luxury Boutique. These terms and conditions outline the rules and regulations for the use of our website and services.

2. Ordering and Purchases
All orders are subject to availability and confirmation of the order price.

3. Returns and Refunds
We take pride in the quality of our luxury items. If you are not entirely satisfied with your purchase, you may return the item in its original condition within 7 days of receipt for an exchange or store credit.

4. Pricing and Availability
While we try and ensure that all details, descriptions, and prices which appear on this Website are accurate, errors may occur.

5. Intellectual Property
The intellectual property rights in all software and content made available to you on or through this Website remains the property of MAMA KAY.

6. Contact Us
If you have any questions about our Terms and Conditions, please contact us.')
ON CONFLICT (key) DO NOTHING;

-- 6. Seed some initial products
INSERT INTO products (name, category, price, description, imageUrl, isAvailable, isFeatured) VALUES
('Elegant Stilettos', 'Shoes', 150000, 'Premium quality stiletto heels designed for elegance and comfort.', '/src/assets/images/luxury_shoes_display_1784626142784.jpg', 1, 1),
('Classic Leather Handbag', 'Bags', 250000, 'A timeless leather handbag perfect for every occasion.', '/src/assets/images/luxury_handbag_1784626142785.jpg', 1, 1)
ON CONFLICT DO NOTHING;
